language: go
install:
  - go get -v github.com/gohugoio/hugo
script:
  - GIT_COMMIT_SHA=`git rev-parse --verify HEAD`
  - GIT_COMMIT_SHA_SHORT=`git rev-parse --short HEAD`
  - hugo -v
deploy:
  - provider: s3
    bucket: emilyburch.com
    acl: public_read
    local_dir: $TRAVIS_BUILD_DIR/emilyburch/public
    on:
      branch: master
  - provider: s3
    bucket: test.emilyburch.com
    acl: public_read
    local_dir: public
    on:
      branch: develop
  - provider: s3
    bucket: test.emilyburch.com
    acl: public_read
    local_dir: public
    on:
      branch: develop
      condition: $TRAVIS_PULL_REQUEST = "true"
