install:
  - wget --quiet https://github.com/gohugoio/hugo/releases/download/v0.25.1/hugo_0.25.1_Linux-64bit.deb
  - sudo dpkg -i hugo_0.25.1_Linux-64bit.deb
script:
  - python --version
  - pip install awscli
  - GIT_COMMIT_SHA=`git rev-parse --verify HEAD` GIT_COMMIT_SHA_SHORT=`git rev-parse --short HEAD` hugo -v
  - aws configure set preview.cloudfront true
deploy:
  provider: script
  script:
    - aws s3 sync --acl "public-read" --sse "AES256" public/ s3://test.emilyburch.com
    on:
      branch: develop
  provider: script
  script:
    - aws s3 sync --acl "public-read" --sse "AES256" public/ s3://pr.emilyburch.com
    on:
      branch: master
      condition: $TRAVIS_PULL_REQUEST = "false"
  provider: script
  script:
    - aws s3 sync --acl "public-read" --sse "AES256" public/ s3://emilyburch.com
    - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths /index.html / /page/* 
    on:
      branch: master
