language: go
install:
  - go get -v github.com/gohugoio/hugo
script:
  - GIT_COMMIT_SHA=`git rev-parse --verify HEAD`
  - GIT_COMMIT_SHA_SHORT=`git rev-parse --short HEAD`
  - python --version
  - pip install awscli
  - hugo -v
  - ./scripts/aws_upload.sh
