version: 0.2

phases:
  install:
    commands:
      - echo Install Hugo
      - pip install hugo
  build:
    commands:
      - echo Build started on `date`
      - hugo -v
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - public/*
