version: 0.2

phases:
  install:
    commands:
      - echo Install Hugo
      - apt-get update -y
      - wget https://github.com/gohugoio/hugo/releases/download/v0.25.1/hugo_0.25.1_Linux-64bit.deb
      - dpkg -i hugo_0.25.1_Linux-64bit.deb
  build:
    commands:
      - echo Build started on `date`
      - hugo -v
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - public/*
